modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GNU LGPLv3"

[[mods]]
modId = "simple_snowy_fix"
version = "${version}"
displayName = "Simple Snowy Fix"
authors = "KostromDan, Apollo"
description = '''
Fixes incorrect snow generation on tree leaves MC-119599
'''
logoFile = "assets/simple_snowy_fix/icon.png"

[[dependencies.simple_snowy_fix]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simple_snowy_fix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
