plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
	id 'net.neoforged.moddev' version '2.0.140' apply false
	id 'net.minecraftforge.gradle' version '[7.0.17,8)' apply false
	id "com.modrinth.minotaur" version "2.+" apply false
	id "net.darkhax.curseforgegradle" version "1.1.+" apply false
}

apply plugin: 'idea'

allprojects {
	apply plugin: 'java-library'
}

jar.enabled = false

subprojects {
	version = project.version
	group = project.maven_group

	base {
		archivesName = project.archives_base_name
	}

	repositories {
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 25
	}

	java {
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
	}
}

task collectJars(type: Copy) {
	dependsOn(
		":fabric:build",
		":neoforge:build",
		":forge:build",
	)

	from("fabric/build/libs") {
		include '*.jar'
	}
	from("neoforge/build/libs") {
		include '*.jar'
	}
	from("forge/build/libs") {
		include '*.jar'
	}

	into("$rootDir/build/libs")
}

build.finalizedBy(collectJars)

task publishUnified {
	group = "upload"
	dependsOn(
			":fabric:publishUnified",
			":neoforge:publishUnified",
			":forge:publishUnified"
	)
}

task publishUnifiedToLocal {
	group = "upload"
	dependsOn(
			":fabric:publishUnifiedToLocal",
			":neoforge:publishUnifiedToLocal",
			":forge:publishUnifiedToLocal"
	)
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}