version=2.2.0
release_type=release

mod_name=Simple Snowy Fix
mod_author=KostromDan, Apollo
mod_id=simple_snowy_fix
mod_description=Fixes incorrect snow generation on tree leaves MC-119599
license=GNU LGPLv3
homepage_url=https://www.curseforge.com/minecraft/mc-mods/simple-snowy-fix-forge-fabric
sources_url=https://github.com/KostromDan/Simple-Snowy-Fix
issues_url=https://github.com/KostromDan/Simple-Snowy-Fix/issues
credits=

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Common Minecraft Properties
minecraft_version=26.1

# Mod Properties
maven_group=dev.kostromdan.mods.simple_snowy_fix
archives_base_name=simple_snowy_fix

# Fabric Properties
# check these on https://fabricmc.net/develop
loader_version=0.18.4
loom_version=1.15-SNAPSHOT
fabric_minecraft_version_range=>=26.0

# NeoForge Properties
# check these on https://projects.neoforged.net/neoforged/neoforge
neo_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)
neo_version_range=[26.0,)
neo_minecraft_version=1.26.1
neo_minecraft_version_range=[26.0,)

forge_version=62.0.1
forge_loader_version_range=[62,)
forge_version_range=[62,)
forge_minecraft_version_range=[26.1,26.2)
