plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id "com.modrinth.minotaur"
    id "net.darkhax.curseforgegradle"
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

base {
    archivesName = "simple_snowy_fix-${project.name}-26.1"
}

minecraft {
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'

    compileOnly project(':common').sourceSets.main.output
}

jar {
    from project(':common').sourceSets.main.output
    manifest {
        attributes([
                "MixinConfigs": "simple_snowy_fix-forge.mixins.json"
        ])
    }
}

processResources {
    def expandProps = [
            "version"                     : project.version,
            "mod_id"                      : project.mod_id,
            "mod_name"                    : project.mod_name,
            "mod_description"             : project.mod_description,
            "mod_author"                  : project.mod_author,
            "license"                     : project.license,
            "credits"                     : project.credits,
            "issues_url"                  : project.issues_url,
            "forge_loader_version_range"  : project.forge_loader_version_range,
            "forge_version_range"         : project.forge_version_range,
            "forge_minecraft_version_range" : project.forge_minecraft_version_range,
    ]
    inputs.properties expandProps
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand expandProps
    }
}

def parsedChangelog = file('../changelog.md').text

if (System.getenv("MODRINTH_TOKEN") != null) {
    modrinth {
        group = "upload"
        token = System.getenv("MODRINTH_TOKEN")
        projectId = "ix1qq8Ux"
        versionNumber = project.version
        versionName = tasks.jar.archiveFile.get().asFile.name
        versionType = release_type
        changelog = parsedChangelog
        uploadFile = tasks.jar
        gameVersions = ["26.1-snapshot-11", "26.1-pre-1", "26.1-pre-2", "26.1-pre-3", "26.1-rc-1", "26.1-rc-2", "26.1-rc-3", "26.1"]
        loaders = ["forge"]
    }
}

if (System.getenv("CF_TOKEN") != null) {
    tasks.register("publishCurseForge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        group = "upload"
        apiToken = System.getenv("CF_TOKEN")

        def mainFile = upload("1154099", tasks.jar)
        mainFile.displayName = tasks.jar.archiveFile.get().asFile.name
        mainFile.changelog = parsedChangelog
        mainFile.changelogType = "markdown"
        mainFile.releaseType = release_type

        mainFile.addGameVersion("26.1")
        mainFile.addModLoader("Forge")
    }
}

task publishUnified {
    group = "upload"
    if (System.getenv("MODRINTH_TOKEN") != null) dependsOn(tasks.modrinth)
    if (System.getenv("CF_TOKEN") != null) dependsOn(tasks.publishCurseForge)
}

task publishUnifiedToLocal(type: Copy) {
    group = "upload"
    dependsOn(tasks.jar)
    from(tasks.jar.archiveFile)
    into("build/unified-local/project0")
}

