plugins {
	id "com.modrinth.minotaur"
	id "net.darkhax.curseforgegradle"
}

apply plugin: 'net.neoforged.moddev'
apply plugin: 'idea'

base {
	archivesName = "simple_snowy_fix-${project.name}-26.1"
}

neoForge {
	version = project.neo_version

	mods {
		"${mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

dependencies {
	// Common project source files for compilation
	compileOnly project(':common').sourceSets.main.output
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
	var replaceProperties = [
			mod_id                        : mod_id,
			mod_name                      : mod_name,
			mod_description               : mod_description,
			mod_author                    : mod_author,
			version                       : version,
			license                       : license,
			credits                       : credits,
			issues_url                    : issues_url,
			neo_version                   : neo_version,
			neoforge_loader_version_range : neoforge_loader_version_range,
			neo_version_range             : neo_version_range,
			neo_minecraft_version_range   : neo_minecraft_version_range,
	]
	inputs.properties replaceProperties
	expand replaceProperties
	from "src/main/templates"
	into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

jar {
	from project(':common').sourceSets.main.output
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}

def parsedChangelog = file('../changelog.md').text

if (System.getenv("MODRINTH_TOKEN") != null) {
	modrinth {
		group = "upload"
		token = System.getenv("MODRINTH_TOKEN")
		projectId = "ix1qq8Ux"
		versionNumber = project.version
		versionName = tasks.jar.archiveFile.get().asFile.name
		versionType = release_type
		changelog = parsedChangelog
		uploadFile = tasks.jar
		gameVersions = ["26.1-snapshot-11", "26.1-pre-1", "26.1-pre-2", "26.1-pre-3", "26.1-rc-1", "26.1-rc-2", "26.1-rc-3", "26.1"]
		loaders = ["neoforge"]
	}
}

if (System.getenv("CF_TOKEN") != null) {
	tasks.register("publishCurseForge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {
		group = "upload"
		apiToken = System.getenv("CF_TOKEN")

		def mainFile = upload("1154099", tasks.jar)
		mainFile.displayName = tasks.jar.archiveFile.get().asFile.name
		mainFile.changelog = parsedChangelog
		mainFile.changelogType = "markdown"
		mainFile.releaseType = release_type

		mainFile.addGameVersion("26.1")
		mainFile.addModLoader("NeoForge")
	}
}

task publishUnified {
	group = "upload"
	if (System.getenv("MODRINTH_TOKEN") != null) dependsOn(tasks.modrinth)
	if (System.getenv("CF_TOKEN") != null) dependsOn(tasks.publishCurseForge)
}

task publishUnifiedToLocal(type: Copy) {
	group = "upload"
	dependsOn(tasks.jar)
	from(tasks.jar.archiveFile)
	into("build/unified-local/project0")
}